version: "3.8"

services:
  db:
    image: postgres:15.10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ${API_IMAGE}
    pull_policy: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-3}
      - GUNICORN_WORKER_CLASS=uvicorn.workers.UvicornWorker
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-30}
      - GUNICORN_KEEP_ALIVE=${GUNICORN_KEEP_ALIVE:-2}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_OPENAI_MODEL=${DEFAULT_OPENAI_MODEL}
      - DEFAULT_ASSISTANT_ID=${DEFAULT_ASSISTANT_ID}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
